In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
data=pd.read_csv('daily demand of POC.csv')
data.head()

,Row Labels,37 pepsi roll,40ml cup,40ml lid,50 lt pty,C.cornto set,chocopaste,citric,CMC,cocont dst,...,mini chocobar wrappers,No.1 CMC,No.1 stick,No.1 suji,orange wrappers,pata,sacarin,stick,suji,swtx
0,2,0,1.0,0.0,0,0,30,3.75,0.00,0,...,25.5,0.0,0,0.0,0.5,0.00,2.75,15,0.00,0.50
1,3,0,0.0,0.0,0,0,0,30.75,0.00,0,...,0.0,0.0,0,0.0,0.0,0.00,2.65,4,5.00,0.00
2,4,0,0.5,0.0,0,0,0,1.75,0.00,1,...,0.0,0.0,0,0.0,0.0,0.00,11.00,0,0.00,0.00
3,5,0,0.5,0.0,0,0,0,3.45,0.00,0,...,0.0,0.0,0,0.0,0.0,0.00,11.65,0,0.00,0.30
4,6,0,0.5,0.0,0,0,0,7.00,0.05,0,...,0.0,0.0,0,0.0,0.0,0.25,1.20,10,0.25,1.25

In [3]:
data['Row Labels']=pd.to_datetime(data['Row Labels'],dayfirst=True)

In [4]:
col=data.columns
col=col.drop('Row Labels')
col
len(col)

25

In [5]:
plt.figure(figsize=(15,25))
k=5
while (k<26):
    j=1
    for i in col[k-5:k]:

        plt.subplot(5,1,j)
        plt.plot(data['Row Labels'],data[i])
        plt.xlabel('Date')
        plt.ylabel('quantity')
        plt.title(i)
        j+=1
    plt.savefig(f'output{k}.jpg')
    plt.clf()   
    k+=5

In [6]:
data_2=pd.read_csv('weekly demand.csv')

,Row Labels,37 pepsi roll,40ml cup,40ml lid,50 lt pty,C.cornto set,chocopaste,citric,CMC,cocont dst,...,mini chocobar wrappers,No.1 CMC,No.1 stick,No.1 suji,orange wrappers,pata,sacarin,stick,suji,swtx
0,2,0,1.0,0.0,0,0,30,3.75,0.00,0,...,25.5,0.0,0,0.0,0.5,0.00,2.75,15,0.00,0.50
1,3,0,0.0,0.0,0,0,0,30.75,0.00,0,...,0.0,0.0,0,0.0,0.0,0.00,2.65,4,5.00,0.00
2,4,0,0.5,0.0,0,0,0,1.75,0.00,1,...,0.0,0.0,0,0.0,0.0,0.00,11.00,0,0.00,0.00
3,5,0,0.5,0.0,0,0,0,3.45,0.00,0,...,0.0,0.0,0,0.0,0.0,0.00,11.65,0,0.00,0.30
4,6,0,0.5,0.0,0,0,0,7.00,0.05,0,...,0.0,0.0,0,0.0,0.0,0.25,1.20,10,0.25,1.25

In [7]:
col=data_2.columns
col=col.drop('Row Labels')
col
len(col)

25

In [8]:
plt.figure(figsize=(15,25))
k=5
while (k<26):
    j=1
    for i in col[k-5:k]:

        plt.subplot(5,1,j)
        plt.plot(data_2['Row Labels'],data_2[i])
        plt.xlabel('Date')
        plt.ylabel('quantity')
        plt.xticks(ticks=np.arange(0,24))
        plt.title(i)
        j+=1
    plt.savefig(f'weekly{k}.jpg')
    plt.clf()   
    k+=5

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
ss=StandardScaler()

In [11]:
'''X1=ss.fit_transform(data['custurd powder'].to_numpy().reshape(-1,1))
X2=ss.fit_transform(data['cocont dst'].to_numpy().reshape(-1,1))'''

In [ ]:
'''plt.plot(data['Row Labels'],X1)
plt.plot(data['Row Labels'],X2)
'''

In [ ]:
'''X3=ss.fit_transform(data_2['custurd powder'].to_numpy().reshape(-1,1))
X4=ss.fit_transform(data_2['cocont dst'].to_numpy().reshape(-1,1))
plt.plot(data_2['Row Labels'],X3)
plt.plot(data_2['Row Labels'],X4)
'''

In [14]:
data_sup=pd.read_csv("weekly supply.csv")
data_sup.head()

,Row Labels,37 pepsi roll,40ml cup,40ml lid,50 lt pty,C.cornto set,chocopaste,citric,CMC,cocont dst,...,mini chocobar wrappers,No.1 CMC,No.1 stick,No.1 suji,orange wrappers,pata,sacarin,stick,suji,swtx
0,41,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0.0,320,0,0
1,42,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,125.0,0,0,0
2,43,0,0,0,0,0,195,0,0,75,...,35,0,0,0,0.0,0,0.0,0,0,0
3,44,0,0,0,0,0,0,0,0,0,...,35,0,0,0,35.0,0,0.0,0,0,0
4,46,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.0,0,0.0,0,0,0

In [15]:
col=data_sup.columns
col=col.drop('Row Labels')
col
len(col)

24

In [16]:
plt.figure(figsize=(15,25))
k=5
while (k<26):
    j=1
    for i in col[k-5:k]:

        plt.subplot(5,1,j)
        plt.plot(data_2['Row Labels'],data_2[i])
        plt.plot(data_sup['Row Labels'],data_sup[i])
        plt.legend(['demand line', 'supply line'])
        plt.xlabel('Date')
        plt.ylabel('quantity')
        plt.xticks(ticks=np.arange(0,24))
        plt.title(i)
        j+=1
    plt.savefig(f'demand&supply{k}.jpg')
    plt.clf()   
    k+=5

In [21]:
col

Index(['37 pepsi roll', '40ml cup', '40ml lid', '50 lt pty', 'C.cornto set',
       'chocopaste', 'citric', 'CMC', 'cocont dst', 'glass cup', 'jack',
       'kulfi wrappers', 'Lily oil', 'milkbar wrappers',
       'mini chocobar wrappers', 'No.1 CMC', 'No.1 stick', 'No.1 suji',
       'orange wrappers', 'pata', 'sacarin', 'stick', 'suji', 'swtx'],
      dtype='object')

In [34]:
data_2.describe()

,Row Labels,37 pepsi roll,40ml cup,40ml lid,50 lt pty,C.cornto set,chocopaste,citric,CMC,cocont dst,...,mini chocobar wrappers,No.1 CMC,No.1 stick,No.1 suji,orange wrappers,pata,sacarin,stick,suji,swtx
count,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.0000,22.000000,...,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000
mean,12.500000,28.409091,10.359091,12.743182,1.227273,7.590909,66.454545,13.343182,4.2250,7.681818,...,48.543636,5.009091,21.136364,5.272727,10.681818,13.936364,16.715909,103.863636,13.843182,27.852273
std,6.493587,28.548470,10.457199,9.638048,2.486761,8.192093,72.582122,9.370284,4.8023,7.815652,...,41.644911,9.061991,46.659144,5.687763,11.481398,13.713516,11.105901,116.894049,12.449845,25.859246
min,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.750000,0.0000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,7.250000,0.500000,1.250000,2.200000,0.000000,0.000000,6.500000,7.037500,0.2125,1.000000,...,5.375000,0.250000,0.000000,0.000000,0.750000,0.312500,9.750000,16.000000,1.875000,0.687500
50%,12.500000,15.000000,7.550000,12.850000,0.000000,5.000000,44.500000,14.000000,2.9750,6.000000,...,49.000000,3.000000,0.000000,4.250000,7.750000,12.250000,16.450000,68.500000,13.650000,24.600000
75%,17.750000,47.750000,16.850000,19.987500,0.750000,14.000000,104.000000,17.312500,5.2750,12.500000,...,75.750000,5.212500,8.750000,8.750000,15.875000,21.050000,23.450000,157.750000,21.150000,45.650000
max,23.000000,78.000000,34.700000,29.200000,8.000000,25.000000,259.000000,38.350000,16.9500,23.000000,...,119.000000,43.250000,160.000000,20.000000,37.000000,41.250000,37.200000,486.000000,39.750000,80.400000

In [ ]:
for i in col:
    sns.barplot(data=data_2,x='Row Labels',y=i)
    plt.axhline(y=data_2[i].mean(),color='green')
    plt.axhline(y=data_2[i].std(),color='red')
    plt.show()

In [38]:
from statsmodels.tsa.stattools import adfuller

In [135]:
weekly_demand=pd.ExcelFile("64E82010.xlsx")
sheet1=pd.read_excel(weekly_demand,'weekly demand')
fortnight=pd.read_excel(weekly_demand,'fortnight demand')
monthly=pd.read_excel(weekly_demand,'monthly demand')

In [143]:
daily=pd.read_excel("daily demand of POC.xlsx")

In [148]:
l={}                                                    #######daily demand trend
m={}
col=daily.columns
col=col.drop('Row Labels')
for i in col:
    result = adfuller(daily[i])
    l[i]=result[0]
    m[i]=result[1]
print('daily demand')
for key2 in m:
    print(f'{key2}:  {m[key2] : .2f}')

daily demand
37 pepsi roll:   0.58
40ml cup:   0.01
40ml lid:   0.00
50 lt pty:   0.00
C.cornto set:   0.00
chocopaste:   0.65
citric:   0.00
CMC:   0.65
cocont dst:   0.00
custurd powder:   0.00
glass cup:   0.00
jack:   0.00
kulfi wrappers:   0.25
Lily oil:   0.00
milkbar wrappers:   0.00
mini chocobar wrappers:   0.08
No.1 CMC:   0.00
No.1 stick:   0.00
No.1 suji:   0.26
orange wrappers:   0.00
pata:   0.00
sacarin:   0.00
stick:   0.00
suji:   0.00
swtx:   0.00

In [149]:
l={}                                                    #######weekly demand trend
m={}
col=sheet1.columns
col=col.drop('Row Labels')
for i in col:
    result = adfuller(sheet1[i])
    l[i]=result[0]
    m[i]=result[1]
print('overall weekly demand')
for key2 in m:
    print(f'{key2}:  {m[key2] : .2f}')

overall weekly demand
37 pepsi roll:   0.00
40ml cup:   0.65
40ml lid:   0.94
50 lt pty:   0.00
C.cornto set:   0.01
chocopaste:   0.00
citric:   0.58
CMC:   0.34
cocont dst:   0.00
custurd powder:   0.60
glass cup:   0.97
jack:   1.00
kulfi wrappers:   0.00
Lily oil:   0.92
milkbar wrappers:   0.56
mini chocobar wrappers:   0.15
No.1 CMC:   0.00
No.1 stick:   0.07
No.1 suji:   0.01
orange wrappers:   0.33
pata:   0.39
sacarin:   0.10
stick:   0.41
suji:   0.60
swtx:   0.72

In [150]:
l={}                                            #######fortnight demand trend
m={}
col=fortnight.columns
col=col.drop('Row Labels')
for i in col:
    result = adfuller(fortnight[i])
    l[i]=result[0]
    m[i]=result[1]
print('fortngiht demand')
for key2 in m:
    print(f'{key2}:  {m[key2] : .2f}')

fortngiht demand
Sum of 37 pepsi roll:   0.65
Sum of 40ml cup:   0.16
Sum of 40ml lid:   0.02
Sum of 50 lt pty:   0.11
Sum of C.cornto set:   0.47
Sum of chocopaste:   0.00
Sum of citric:   0.00
Sum of CMC:   0.41
Sum of cocont dst:   0.04
Sum of custurd powder:   0.05
Sum of glass cup:   0.17
Sum of jack:   0.60
Sum of kulfi wrappers:   0.06
Sum of Lily oil:   0.46
Sum of milkbar wrappers:   0.32
Sum of mini chocobar wrappers:   0.01
Sum of No.1 CMC:   0.03
Sum of No.1 stick:   0.16
Sum of No.1 suji:   0.27
Sum of orange wrappers:   0.77
Sum of pata:   0.27
Sum of sacarin:   0.00
Sum of stick:   0.25
Sum of suji:   0.20
Sum of swtx:   0.05

In [151]:
l={}                                            #######monthly demand trend
m={}
col=monthly.columns
col=col.drop('Row Labels')
for i in col:
    result = adfuller(monthly[i])
    l[i]=result[0]
    m[i]=result[1]
print('fortngiht demand')
for key2 in m:
    print(f'{key2}:  {m[key2] : .2f}')

fortngiht demand
37 pepsi roll:   0.72
40ml cup:   0.49
40ml lid:   0.04
50 lt pty:   0.43
C.cornto set:   0.37
chocopaste:   0.57
citric:   0.51
CMC:   0.59
cocont dst:   0.33
custurd powder:   0.30
glass cup:   0.10
jack:   0.80
kulfi wrappers:   0.34
Lily oil:   0.60
milkbar wrappers:   0.70
mini chocobar wrappers:   0.46
No.1 CMC:   0.28
No.1 stick:   0.28
No.1 suji:   0.53
orange wrappers:   0.69
pata:   0.64
sacarin:   0.65
stick:   0.46
suji:   0.58
swtx:   0.59

In [73]:
#load the required libraries
import numpy as np
import pandas as pd
# Load Statsmodels 
import statsmodels.api as sm
# Load Matplotlib for visualization
import matplotlib.pyplot as plt
%matplotlib inline

In [88]:
#loading data
data=pd.ExcelFile("demand trend3.xlsx")
day_data=pd.read_excel(data,'daily demand')
week_data=pd.read_excel(data,'weekly demand')
twoweeks_data=pd.read_excel(data,'fortnight demand')
month_data=pd.read_excel(data,'monthly demand')

In [89]:
week_data=day_data

In [90]:
week_data.index=week_data['Row Labels']
del week_data['Row Labels']

In [ ]:
"""plt.figure(figsize=(16,5))

for i in week_data.columns:
    plt.plot(week_data.index, week_data[i], label = f"{i}")
    plt.legend(loc='best')
    plt.title(f"weekly demand of {i}")
    plt.show()"""

In [91]:
week_data.columns

Index(['37 pepsi roll', '40ml cup', '40ml lid', '50 lt pty', 'C.cornto set',
       'chocopaste', 'citric', 'CMC', 'cocont dst', 'custurd powder',
       'glass cup', 'jack', 'kulfi wrappers', 'Lily oil', 'milkbar wrappers',
       'mini chocobar wrappers', 'No.1 CMC', 'No.1 stick', 'No.1 suji',
       'orange wrappers', 'pata', 'sacarin', 'stick', 'suji', 'swtx'],
      dtype='object')

In [92]:
import os
file=open('day_adf_data.csv','w')
for i in week_data.columns:
    file.write(i)
    file.write(',')
    result=adfuller(week_data[i],autolag='AIC')
    n=len(result[0:4])
    for j in range(n) :
        if j==n:
            file.write(str(result[j]))
        else:
            file.write(str(result[j]))
            file.write(',')
    m=0    
    for key,value in result[4].items():
        if m<2:
            file.write(str(value))
            file.write(',')
            m+=1
        else:
            file.write(str(value))

    file.write('\n')
file.close()

In [94]:
ad_data=pd.ExcelFile('adf_data.xlsx')
daily=pd.read_excel(ad_data,'day_adf_data')

In [95]:
daily.head()

,'item_name','Test Statistic','p-value','#Lags Used','Number of Observations Used','1%','5%','10%',Remarks
0,37 pepsi roll,-1.401745,5.814393e-01,10,111,-3.490683,-2.887952,-2.580857,Non Stationary
1,40ml cup,-3.457072,9.160484e-03,3,118,-3.487022,-2.886363,-2.580009,Stationary
2,40ml lid,-10.610508,5.850624e-19,0,121,-3.485585,-2.885739,-2.579676,Stationary
3,50 lt pty,-9.506803,3.330460e-16,0,121,-3.485585,-2.885739,-2.579676,Stationary
4,C.cornto set,-9.248814,1.511673e-15,0,121,-3.485585,-2.885739,-2.579676,Stationary

In [58]:
adf.head()

,item_name,Test Statistic,p-value,#Lags Used,Number of Observations Used,1%,5%,10%
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
ad_data

,'item_name','Test Statistic','p-value','#Lags Used','Number of Observations Used','1%','5%','10%',Remarks
0,37 pepsi roll,-3.927910,1.838784e-03,9,12,-4.137829,-3.154972,-2.714477,Stationary
1,40ml cup,-1.264523,6.452428e-01,2,19,-3.832603,-3.031227,-2.655520,Non Stationary
2,40ml lid,-0.169772,9.420301e-01,9,12,-4.137829,-3.154972,-2.714477,Non Stationary
3,50 lt pty,-3.836583,2.554437e-03,0,21,-3.788386,-3.013098,-2.646397,Stationary
4,C.cornto set,-3.503498,7.897701e-03,9,12,-4.137829,-3.154972,-2.714477,Stationary
5,chocopaste,-3.656072,4.775225e-03,7,14,-4.012034,-3.104184,-2.690987,Stationary
6,citric,-1.405815,5.794853e-01,9,12,-4.137829,-3.154972,-2.714477,Non Stationary
7,CMC,-1.893057,3.353342e-01,0,21,-3.788386,-3.013098,-2.646397,Non Stationary
8,cocont dst,-9.726625,9.237412e-17,9,12,-4.137829,-3.154972,-2.714477,Stationary
9,custurd powder,-1.365325,5.987824e-01,9,12,-4.137829,-3.154972,-2.714477,Non Stationary
10,glass cup,0.196753,9.720789e-01,9,12,-4.137829,-3.154972,-2.714477,Non Stationary
11,jack,29.718595,1.000000e+00,9,12,-4.137829,-3.154972,-2.714477,Non Stationary
12,kulfi wrappers,-5.487709,2.210743e-06,9,12,-4.137829,-3.154972,-2.714477,Stationary
13,Lily oil,-0.339926,9.196562e-01,8,13,-4.068854,-3.127149,-2.701730,Non Stationary
14,milkbar wrappers,-1.440592,5.626686e-01,9,12,-4.137829,-3.154972,-2.714477,Non Stationary
15,mini chocobar wrappers,-2.382429,1.467573e-01,7,14,-4.012034,-3.104184,-2.690987,Non Stationary
16,No.1 CMC,-4.493881,2.017072e-04,0,21,-3.788386,-3.013098,-2.646397,Stationary
17,No.1 stick,-2.738243,6.765113e-02,9,12,-4.137829,-3.154972,-2.714477,Non Stationary
18,No.1 suji,-3.506164,7.830203e-03,9,12,-4.137829,-3.154972,-2.714477,Stationary
19,orange wrappers,-1.908935,3.278697e-01,9,12,-4.137829,-3.154972,-2.714477,Non Stationary
20,pata,-1.785514,3.876767e-01,9,12,-4.137829,-3.154972,-2.714477,Non Stationary
21,sacarin,-2.553281,1.030426e-01,0,21,-3.788386,-3.013098,-2.646397,Non Stationary
22,stick,-1.747684,4.067265e-01,6,15,-3.964443,-3.084908,-2.681814,Non Stationary
23,suji,-1.353734,6.042450e-01,9,12,-4.137829,-3.154972,-2.714477,Non Stationary
24,swtx,-1.094200,7.173793e-01,9,12,-4.137829,-3.154972,-2.714477,Non Stationary

In [38]:
adf.head()

,Test Statistic,p-value,#Lags Used,Number of Observations Used,1%,5%,10%
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:

# Load the dataset
df = sm.datasets.sunspots.load_pandas().data
# Check the dimensionality of the dataset
df.shape
print("Dataset has {} records and {} columns".format(df.shape[0], df.shape[1]))
# Changing the YEAR data type and setting it as index
df['YEAR'] = pd.Index(sm.tsa.datetools.dates_from_range('1700', '2008'))
df.index = df['YEAR']
# Check the data type
del df['YEAR']
# View the dataset
df.head()
# Plotting the Data
# Define the plot size
plt.figure(figsize=(16,5))
# Plot the data
plt.plot(df.index, df['SUNACTIVITY'], label = "SUNACTIVITY")
plt.legend(loc='best')
plt.title("Sunspot Data from year 1700 to 2008")
plt.show()
# ADF Test
# Function to print out results in customised manner
from statsmodels.tsa.stattools import adfuller
def adf_test(timeseries):
    print ('Results of Dickey-Fuller Test:')
    dftest = adfuller(timeseries, autolag='AIC')
    dfoutput = pd.Series(dftest[0:4], index=['Test Statistic','p-value','#Lags Used','Number of Observations Used'])
    for key,value in dftest[4].items():
        dfoutput['Critical Value (%s)'%key] = value
    print (dfoutput)
# Call the function and run the test

adf_test(df['SUNACTIVITY'])